version: '3.8'
services:
  openvpn:
    container_name: openvpn
    image: docker.pkg.github.com/inteclab/openvpn/openvpn:latest
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
     - "9988:9988/tcp"
#    network_mode: "host"
    restart: always
    volumes:
     - /lab/data/docker/volume/openvpn-data:/etc/openvpn
    networks:
      openvpn:
        ipv4_address: 10.2.1.199

networks:
  openvpn:
    ipam:
      config:
        - subnet: 10.2.0.0/16
  # default:
  #   external:
  #     name: lab_default
